<footer>
    <a><img class="social" src="medias/commun/facebook.jpg" alt="Facebook" /></a>
    <a><img class="social" src="medias/commun/instagram.jpg" alt="Instagram" /></a>
    <a><img class="social" src="medias/commun/linkedin.jpg" alt="LinkedIn" /></a>
    <div style="text-align: center;"></div>
    <p class="copyright"><a href="https://mailbakery.com/template-store/product/bloom-free-html-email-template">Bloom!</a> - Free HTML Template</p>
    <p class="copyright">Site Web par Léandre Kanmegne
    <?php
        echo date("Y");
    ?>
    </p>
</footer>